# Generated by Django 5.2 on 2025-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_courseregistration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='last_applied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
