# Generated by Django 5.2 on 2025-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_courseregistration_last_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='last_applied',
            field=models.DateTimeField(default=''),
        ),
    ]
