# Generated by Django 5.2 on 2025-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_courseregistration_last_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
