# Generated by Django 5.2 on 2025-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blog_author_alter_blog_author_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
