# Generated by Django 5.2 on 2025-04-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_blog_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_description',
        ),
    ]
