# Generated by Django 5.2 on 2025-04-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_blog_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
