# Generated by Django 5.2 on 2025-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_blog_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='author_images/default.jpg', upload_to='author_images/'),
        ),
    ]
