# Generated by Django 5.2 on 2025-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_blog_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
