# Generated by Django 5.2 on 2025-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_testimonialslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='images/'),
        ),
    ]
