# Generated by Django 5.2 on 2025-04-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_image',
        ),
    ]
